FROM tebanep/odoo-data
MAINTAINER Esteban Echeverry <tebanep@gmail.com>

# Add the PostgreSQL PGP key to verify their Debian packages.
# It should be the same key as https://www.postgresql.org/media/keys/ACCC4CF8.asc
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8

# Add PostgreSQL's repository. It contains the most recent stable release
# of PostgreSQL, ``9.3``.
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" > /etc/apt/sources.list.d/pgdg.list
RUN cat /usr/sbin/policy-rc.d

# Add VOLUMEs to allow backup of config, logs and databases
VOLUME ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

# Remove /usr/sbin/policy-rc.d which prevents PostgreSQL to start after installation
RUN rm /usr/sbin/policy-rc.d

# Adjust PostgreSQL configuration so that remote connections to the
# database are possible.
RUN mkdir -p /etc/postgresql/9.3/main/
#RUN chown -R postgres:postgres /etc/postgresql/9.3/main

RUN ls -l /etc/postgresql

RUN echo "host all  all    0.0.0.0/0  md5" >> /etc/postgresql/9.3/main/pg_hba.conf

# And add ``listen_addresses`` to ``/etc/postgresql/9.3/main/postgresql.conf``
RUN echo "listen_addresses='*'" >> /etc/postgresql/9.3/main/postgresql.conf




# Install ``python-software-properties``, ``software-properties-common`` and PostgreSQL 9.3
# There are some warnings (in red) that show up during the build. You can hide
# them by prefixing each apt-get statement with DEBIAN_FRONTEND=noninteractive
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y python-software-properties \
    software-properties-common postgresql-9.3 postgresql-client-9.3 postgresql-contrib-9.3






# Run the rest of the commands as the ``postgres`` user
USER postgres
# Create a PostgreSQL role named ``odoo`` with ``odoo`` as the password and
# then create a database `odoo` owned by the ``odoo`` role.

#RUN /etc/init.d/postgresql start && \
#	psql --command "CREATE USER odoo WITH CREATEDB SUPERUSER PASSWORD 'odoo';" && \
#	createdb -O odoo odoo






# Expose the PostgreSQL port
EXPOSE 5432

# Set the default command to run when starting the container
CMD ["/usr/lib/postgresql/9.3/bin/postgres", "-D", "/var/lib/postgresql/9.3/main", "-c", "config_file=/etc/postgresql/9.3/main/postgresql.conf"]
