FROM tebanep/odoo-ubuntu
#FROM busybox:ubuntu-14.04
MAINTAINER Esteban Echeverry <tebanep@gmail.com>

#RUN mkdir -p /etc/postgresql
#RUN mkdir -p /var/log/postgresql
#RUN mkdir -p /var/lib/postgresql
#RUN mkdir -p /var/lib/postgresql/data

#RUN mkdir -p /opt/odoo/addons
#RUN mkdir -p /var/log/odoo

#VOLUME ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql", \
#        "/var/lib/postgresql/data", "/opt/odoo/addons", "/var/log/odoo"]

ENTRYPOINT ["/bin/bash"]
